version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    steps:

      - checkout
      
      - run:
          name: Build JAR
          command: |
            ls -al
            cd LambdaApp/
            ls -al
            mvn clean install
            cd target
            ls -al
            cd ../../
            ls -al
      - run :
          name : Install pip
          command: |
            sudo apt-get update || sudo apt-get update
            sudo apt-get install python3
            python3 --version
            sudo apt install python3-pip
            pip3 --version
      - run :
          name  :   AWS CLI Install 
          command :  sudo pip3 install awscli

      - run:
          name: Zip Artifact
          command: |
            echo "The current build number is ${CIRCLE_BUILD_NUM}"
            pwd
            echo "Listing current directory content"
            ls -al
            echo "Making the lambda_deploy_artifact directory"
            mkdir -p lambda_deploy_artifact
            echo "Changing directory to lambda_deploy_artifact"
            cd lambda_deploy_artifact
            echo "Copying the jar file from ../LambdaApp/target/original-lambdaapp-1.0-SNAPSHOT.jar to the lambda_deploy_artifact"
            cp ../LambdaApp/target/original-lambdaapp-1.0-SNAPSHOT.jar .
            chmod -R 777 original-lambdaapp-1.0-SNAPSHOT.jar
            
            ls -al
            pwd
            echo "Changing directory to root"
            cd ..
            pwd
            ls -al

      - run:
          name: Update Lambda Function zip
          command: |
            cd lambda_deploy_artifact
            pwd
            ls -al
            
            export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            export AWS_DEFAULT_REGION=us-east-1
            aws lambda update-function-code --function-name lambdaapp \
            --zip-file fileb://original-lambdaapp-1.0-SNAPSHOT.jar

workflows:
  version: 2
  build:
    jobs:
    - build: {}
